---
title: "Identificar as variáveis/fatores socioeconômicos que influenciam na aprovação ou não dos candidatos inscritos no ENEM em 2017"
author: "Marcos Antonio Euzebio de Oliveira"
output: pdf_document
toc: T
number_sections: T
---

# 1 INTRODUÇÃO

O Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP), por intermédio da Diretoria de Avaliação da Educação Básica, em cumprimento da sua missão de desenvolver e disseminar informações sobre os exames e avaliações da educação básica, disponibiliza os Microdados do Enem 2017.

## 1.1 Delimitação do tema

A educação no Brasil passou por muitas mudanças, principalmente nas ultimas décadas, onde houve por exemplo a expansão no número de instituições (tanto privadas quanto públicas) e ampliação de acesso. O ENEM se consolida, nesse cenário, como principal acesso ao ensino superior. Ele tem também como proposta ser uma ferramenta de autoavaliação das habilidades desenvolvidas pelo aluno ao final do ensino médio. 

O desenvolvimento de tais habilidades pode ser atribuída ao esforço do aluno, porém há de se considerar fatores externos que possam inlfuenciar seu desempenho. Heranças recebidas pelos alunos, não necessáriamente monetárias, são variáveis que influenciam o apendizado segundo Bourdieu (1986), sendo elas variáveis latentes. A infraestrutura escolar é um fator importante neste contexto, bem como o contexto social em que o estudante está inserido.

O ENEM, bem como o Censo Escolar forncecem informações necessárias para o presente estudo, sendo levado em consideração o ambiente familiar e escolar. O efeito da turma do aluno, no caso ano-série por exemplo, também é um fator influente, porém não temos tal informação a partir dos dados disponíveis.

## 1.2 Objetivos

O objetivo geral deste trabalho é analisar quais variáveis socioeconomicas influenciaram os estudantes que fazeram o ENEM no estado do Paraná no ano de 2017, sendo utilizada uma modelagem multinivel


# 2 Revisão Bibliográfica

## 2.1 Sobre história da educação

A educação no Brasil se inicia com a chegada dos jesuítas como primeiros educadores, a partir de 1549. SAVIANI (2011) define esse como o primeiro período educacional no Brasil, marcado pelos princípios colonizador e catequizador, com ênfase nos povos indígenas. Neste período, os colonizadores ao tentar escravizar indígenas, foram confrontados pelos jesuítas.

No segundo período, a fim de acabar com tal embate, Marquês de Pombal determina a expulsão dos jesuítas do terrítorio nacional na segunda metade do século XVIII, reduzindo a influência dos padres no ensino brasileiro. Neste momento, é fomentada a discussão sobre propostas de ensino, tendo os métodos intuitivo e o mútuo ganhado espaço. A Lei de 15 de outubro de 1827 cria as "escolas de primeiras letras" em todas as cidades, vilas e lugares mais populosos do Império, onde tais métodos passam a ser utilizados.

No período seguinte, buscou-se o equilíbrio entre a pedagogia tradicional e a pedagogia nova. Pensadores educacionais começam a olhar o indivíduo como sendo o foco do aprendizado, culminando no __Manifesto dos Pioneiros da Educação Nova__. Neste período, é encaminhado o primeiro projeto sobre  as Lei de Diretrizes e Bases da Educação Nacional ao Congresso Nacional, sendo aprovado apenas na década de 1960.

No quarto período, junto a ditadura militar, foi difundida a pedagogia tecnicista, a qual privilegiava excessivamente a tecnologia educacional e transformava professores e alunos em meros executores e receptores de projetos elaborados de forma autoritária e sem qualquer vínculo com o contexto social a que se destinavam. Porém, é neste período que a pedagogia crítica ganha força. Baseada na teoria marxista, ela objetiva habilitar o estudante a pensar criticamente quanto a sua realidade, sendo suas ideias opostas às do regime militar. Nesta época também nascem organizações como a Associação Nacional de Educação (ANDE), Associação Nacional de Pós-Graduação e Pesquisa em Educação (ANPEd), Centro de Estudos Educação e Sociedade (CEDES), fortalecendo a Confederação de Professores do Brasil (CPB), que, posteriormente, torna-se a Confederação Nacional dos Trabalhadores da Educação (CNTE). Tais associações docentes, apoiando-se no momento nacional, passam a estabelecer laços sindicais. Tudo isso ajuda a fortalecer a produção científica preocupada com "a construção de uma escola pública de qualidade" (SAVIANI, 2011,p. 402). Também nesta época, com a transição do fordismo para o toyotismo, as idéias pedagógicas no Brasil se manifestam no neoprodutivismo, tratando o conhecimento como um bem do aluno na forma de capital humano, o que acaba se transformando na "pedagogia da exclusão". O neoescolanovismo reascende a ideia de "aprender a aprender", sendo essa uma atividade construtiva do aluno. O Estado passa a tentar maximizar seus resultados educacionais reorganizando suas formas de ensino.  

## 2.2 O ENEM

Criado em 1998, o Exame Nacional do Ensino Médio (Enem) tem como objetivo verificar se seus participantes apresentam domínio dos princípios científicos e tecnológicos ao final do ensino médio, domínio dos princípios científicos e tecnológicos que presidem a produção moderna e se detêm conhecimento das formas contemporâneas de linguagem. 
Seus resultados deverão possibilitar: 

I - a constituição de parâmetros para a autoavaliação do participante, com vistas à continuidade de sua formação e a sua inserção no mercado de trabalho; 

II - a criação de referência nacional para o aperfeiçoamento dos currículos do ensino médio; 

III - a utilização do Exame como mecanismo único, alternativo ou complementar para acesso à educação superior, especialmente a ofertada pelas instituições federais de educação superior;

IV - o acesso a programas governamentais de financiamento ou apoio ao estudante da educação;

V - a sua utilização como instrumento de seleção para ingresso nos diferentes setores do mundo do trabalho;
 
VI - o desenvolvimento de estudos e indicadores sobre a educação brasileira. 

O exame já era utilizado por algumas instituições de Ensino Superior como instrumento de seleção para o ingresso de estudantes, quando em 2009 passou pela reformulação a fim de democratizar o acesso. A partir de então muitas outras universidades federais passaram a utilizá-lo como método de ingresso através do SISU. Reformularam-se as Matrizes de Referência do Exame, que passaram a ser estruturadas por competências em quatro áreas do conhecimento – Linguagens, Códigos e suas Tecnologias, Matemática e suas Tecnologias, Ciências Humanas e suas Tecnologias e Ciências da Natureza e suas Tecnologias –, apresentando, ainda, eixos cognitivos comuns a todas as áreas. Essa mesma reformulação permitiu que obedecendo a Lei de Diretrizes e Bases da Educação Nacional (Lei 9.394/1996), alunos pudessem utilizar a prova como certificação de conclusão do Ensino Médio, porém em 2017 a prova deixou de ter esta atribuição.

Em 2017 a prova contou com 180 questões e uma proposta de redação, sendo aplicadas em dois domingos seguidos, porém em edições anteriores ela foi aplicada em dois dias seguidos (sábado e domingo). No primeiro dia, os estudantes recebem  um caderno de questões com com as provas de Linguagens, Códigos e suas Tecnologias e Redação e de Ciências Humanas e suas Tecnologias, já no segundo dia um caderno com as provas Ciências da Natureza e suas Tecnologias e Matemática e suas Tecnologias. A Tabela 1 apresenta uma descrição das Áreas de conhecimento e componentes curriculares do ENEM.

##### **Tabela 1** – Descrição das Áreas de Conhecimento e Componentes Curriculares do Enem.


| Área do conhecimento 	| Componentes Curriculares 	|
|:---------------------------------------:	|:-----------------------------------------------------------------------------------------------------------------------------------------:	|
| Linguagens, Códigos e suas tecnologias 	| Língua Portuguesa, Literatura, Língua Estrangeira (Inglês ou Espanhol), Artes, Educação Física e Tecnologias da Informação e Comunicação. 	|
| Ciências Humanas e suas tecnologias 	| História, Geografia, Filosofia e Sociologia. 	|
| Ciências da Natureza e suas tecnologias 	| Química, Física e Biologia. 	|
| Matemática e suas tecnologias 	| Matemática. 	|

**Nota Fonte**:  Adaptado do Enem (2017)

Houve ainda uma segunda aplicação do Enem 2017, ocorrendo nos dias 12 e 13 de dezembro de 2017. Esta data foi destinada para Pessoas Privadas de Liberdade e Jovens sob Medida Socioeducativa que inclua privação de liberdade – PPL, e também  a participantes com direito à reaplicação.
Neste ano além das provas objetivas e da redação, os participantes do Enem respondem a um questionário que contempla questões sobre seu nível socioeconômico, família, educação e trabalho, havendo uma diminuição no número de questões do questionário, contemplando 27 questões no total.

## 2.3 Estudos sobre o ENEM

Figueirêdo, Nogueira e Santana (2014) investigaram como o background de um indivíduo que realiza ENEM influência em seu desempenho. Para isso, consideraram variáveis como a renda familiar, a escolaridade dos pais, se estudou em escola pública ou privada, a raça, se mora na área urbana ou rural e o índice de qualidade escolar do SAEB.
Duas abordagens foram tomadas: a primeira assume que o esforço do indivíduo e as circunstâncias em que ele se encontra, ou em que as variáveis foram mensuradas, são independentes. A segunda relaxa essas hipóteses, ou seja, considera que pode existir uma relação entre essas quantidades. Esses modelos foram baseados em estudos realizados anteriormente por Roemer(1998) e Hanushek(1970, 1979, 2007).
As técnicas utilizadas para mensurar o assunto são baseadas no modelo de classificação não paramétrico, Axioma de Identificação de Roemer, proposto por Roemer e na função de produção educacional, de Hanushek.
Figueirêdo, Nogueira e Santana (2014) concluíram que as variáveis socioeconômicas consideradas influenciam diretamente no esforço do indivíduo e, consequentemente na sua pontuação. Indivíduos de “baixo background” têm de se esforçar 99,38% mais do que aqueles que possuem “alto background” para terem as mesmas chances de sucesso no exame. Por isso, parece inviável que aqueles participantes penalizados pelas circunstâncias obtenham as melhores notas. Esses resultados são ainda mais extremos na Região Nordeste.
 
Monteiro, Cavalcanti e Ostermann (2018) se baseiam nas ideias de Pierre Bourdieu e descrevem que o aprendizado é influenciado por heranças  culturais advindas do convívio social , constituem o que Bourdieu chama de capital cultural, capital econômico (bens materiais, propriedades e outros) e o capital social (relações sociais com pessoas chave, prestígio, poder político). Capitais culturais  seriam o que a pessoa possui que não é mensurado em objetos ou dinheiro, seriam mais relacionados a traços psicológicos, sendo tais que identifica três estados nos quais esse capital pode ser encontrado: institucionalizado, objetivado e incorporado. . O estado institucionalizado corresponde aos títulos escolares acumulados pelo estudante. O estado objetivado consiste dos bens culturais que o sujeito tem acesso, como livros, revistas, enciclopédias e obras de arte, por exemplo. O mais importante dos estados certamente é o incorporado. A partir desta perspectiva o autor espera encontrar que as variáveis mais importantes estão associados aos capitais culturais incorporados.
Começam separando os alunos em níveis socioeconômicos através da análise fatorial completa, onde permite separar as questões socioeconômicas em 3 fatores(que coincidiram com os propostos por Bourdieu) e usar o peso destes fatores para representar  os estados, dentre os quais foi utilizado o correspondente ao capital cultural institucionalizado, pois está mais correlacionado com a nota. A partir de tais variáveis, foi utilizada a análise de cluster para se construir níveis socioeconômicos através do método de K-means bivariada.
Para analisar a dificuldade da questão, os autores usam um modelo logístico de 3 variáveis, para determinar a dificuldade da questão.



\newpage

# Referências

BRASIL/MEC. Lei nº. 9.394, de 20 de dezembro de 1996. Lei de Diretrizes e Bases da Educação Nacional. Brasília, DF: 20 de dezembro de 1996. 

INSTITUTO NACIONAL DE ESTUDOS E PESQUISAS EDUCACIONAIS ANÍSIO TEIXEIRA. Microdados do Enem 2017. Brasília: Inep, 2017. Disponível em: < http://portal.inep.gov.br/web/guest/microdados>. Acesso em: 01 nov. 2017.

NERY,Thiago Ribeiro. Infraestrutura das escolas como fator em um modelo multinível das
proficiências dos alunos do ensino médio (Dissertação em estatística) – ENCE. Rio de Janeiro. 2017.

SAVIANI, Dermeval. História das ideias pedagógicas no Brasil. Campinas, Autores Associados, 2011.

FIGUEIRÊDO, Erik; NOGUEIRA, Lauro; SANTANA, Fernanda Leite. Igualdade de Oportunidades: Analisando o papel das circunstâncias no
desempenho do ENEM. Revista Brasileira de Economia, v. 68, n. 3, p. 373-392, 2014.

MONTEIRO, Matheus;  Cavalcanti, Cláudio; Ostermann, Fernanda; Uma busca por questões de Física do ENEM potencialmente não reprodutoras das desigualdades socioeconômicas. Rev. Bras. Ensino Fís. vol.40 no.3 São Paulo  2018  Epub Jan 18, 2018.

P. Bourdieu, in: Handbook of Theory and Research for the Sociology of Education, edited by J. Richardson (Greenwood, New York, 1986), p. 241.

RODRIGUES, Erica Castilho; MATOS, Daniel Abud Seabra; FERREIRA, Aline dos Santos. Nível socioeconômico e ensino superior: cálculo e aplicações. Avaliação (Campinas),  Sorocaba ,  v. 22, n. 2, p. 494-511,  Aug.  2017 .   Disponível em <http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1414-40772017000200494&lng=en&nrm=iso>. acesso em on  01  Outubro.  2018.  http://dx.doi.org/10.1590/s1414-40772017000200013.
